name: Lambda Deployment Workflow
on:
  push:
    branches:
      - master 
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 
      - name: Zip Lambda code
        run: |
          zip -r sum_lambda.zip . -i sum_lambda.py
      - name: Upload Lambda code to S3
        run: aws s3 cp ./sum_lambda.zip s3://sc-lambda-product/sum_lambda.zip  
      - name: Call Service Catalog to deploy Lambda
        run: |
          aws servicecatalog provision-product \
          --product-id prod-vhxh5q35kvy3s \
          --provisioning-artifact-id pa-mcpgxpvdsig3q \
          --provisioned-product-name "LambdaDeployment"