name: Lambda Deployment Workflow
on:
  push:
    branches:
      - master 
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Zip Lambda code
        run: |
          zip -r hello.zip . -i hello.py
      - name: Upload Lambda code to S3
        run: aws s3 cp ./hello.zip s3://my-lambda-product-bucket/hello.zip      # Use AWS CLI or SDK to upload Lambda code to S3 bucket
      - name: Call Service Catalog to deploy Lambda
        run: |
          PRODUCT_ID="prod-zzvrxsnmem6ac"
          PROVISIONING_ARTIFACT_ID="pa-lbfqtugwyj4j4"
          aws servicecatalog create-provisioned-product-plan \
            --product-id $PRODUCT_ID \
            --plan-name "LambdaDeployment" \
            --plan-type "CLOUDFORMATION" \
            --provisioning-artifact-id $PROVISIONING_ARTIFACT_ID \
            --provisioned-product-name "LambdaDeployment" \
            --provisioning-parameters "Key=LambdaS3Bucket,Value=my-lambda-product-bucket,UsePreviousValue=false" \
            "Key=LambdaS3Key,Value=hello.zip,UsePreviousValue=false" \
            --region ap-south-1