name: Lambda Deployment Workflow
on:
  push:
    branches:
      - master 
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Zip Lambda code
        run: |
          zip -r hello.zip . -i hello.py
      - name: Upload Lambda code to S3
        run: aws s3 cp ./hello.zip s3://my-lambda-product-bucket/hello.zip  
      - name: Call Service Catalog to deploy Lambda
        run: |
          aws servicecatalog provision-product \
          --product-id prod-h7oqydmiqudg4 \
          --provisioning-artifact-id pa-zxtrgu7lqjhju \
          --provisioned-product-name "LambdaDeployment"

        # PRODUCT_ID="prod-76kjj76mksur6"
          # PROVISIONING_ARTIFACT_ID="pa-tnnkdka6sb7lo"
          # aws servicecatalog create-provisioned-product-plan \
          #   --product-id $PRODUCT_ID \
          #   --plan-name "LambdaDeployment" \
          #   --plan-type "CLOUDFORMATION" \
          #   --provisioning-artifact-id $PROVISIONING_ARTIFACT_ID \
          #   --provisioned-product-name "LambdaDeployment"